name: Generate Daily Puzzle
on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with: { 'node-version': '18' }

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Generate puzzle
        run: |
          cd web
          node scripts/generateDaily.js

      - name: Commit and push puzzle
        run: |
          cd web
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/daily-puzzles.json
          git commit -m "Daily puzzle for $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push

      - name: Deploy to GitHub Pages
        run: |
          cd web
          npm run build
          npm run deploy

